e='hello'
print(e)
a="Childeren's Day"
print(a)
m= "today is new day"
m1=m.split(" ")
print(m1)
print(m)
a='childeren\'s Day'
print(a)
print(len(a))
print(a[0])
print(a[4:9])
print(a[4:])
print(a.lower())
print(a.upper())
print(a.count('e'))
print(a.find('l'))
b=a.replace('Day','Month')
print(b)
print(b+' '+e)
print('{},{}.{};hi'.format(a,b,e))
print(f'{a},{b.upper()}.{e}')
print(dir(a))
print(help(str))
print(help(str.lower))